package com.knowre.android.myscript.iink.view.candidate


val getPreDefinedCandidates = { label: String ->
    preDefinedCandidatesMap[label] ?: listOf()
}

private val preDefinedCandidatesMap = hashMapOf(
    Pair("0", listOf("O", "0", "o", "∘", "∫", "·", ".")),
    Pair("1", listOf("1", "|", "I", "l", "ι", "i", "t", "(", "+")),
    Pair("2", listOf("2", "z", "Z", "1", "=", "3", "r", "a")),
    Pair("3", listOf("3", "ζ", "}", "s", "1", "2", "z", "5")),
    Pair("4", listOf("4", "q", "9", "y", "a", "g", "cl")),
    Pair("5", listOf("5", "s", "E", "J", "ζ", "[", "F", "f", "S", "tan")),
    Pair("6", listOf("6", "b", "f", "t", "G", "8", "(", "L")),
    Pair("7", listOf("7", "T", "τ", "2", "I", "ζ", "1", "r")),
    Pair("8", listOf("8", "g", "f", "s", "S", "δ", "&", "G", "5", "sin")),
    Pair("9", listOf("9", "q", "a", "g", "G", "4", "ℚ", "cl")),

    Pair("a", listOf("a", "α", "G", "A", "q", "d", "o", "n", "∝", "cl")),
    Pair("b", listOf("b", "h", "6", "k", "ha", "tan")),
    Pair("c", listOf("c", "C", "⊂", "a", "<", "2", "(", "o", "∠")),
    Pair("d", listOf("d", "h", "k", "dx", "a", "α", "2", "λ", "t", "x")),
    Pair("e", listOf("e", "c", "C", "l", "2", "r", "E", "a")),
    Pair("f", listOf("f", "t", "+", "F", "1", "l")),
    Pair("y", listOf("g", "y", "t", "q", "8", "f", "z", "2", "J", "r", "sin")),
    Pair("h", listOf("h", "k", "K", "n", "4", "b", "t", "κ", "1", "hl")),
    Pair("i", listOf("i", "I", "1", "j", "T", ";", "'", "t", "+")),
    Pair("j", listOf("j", "J", ")", "i", "I", ",", "g", "]", "1")),
    Pair("k", listOf("k", "K", "κ")),
    Pair("l", listOf("l", "t", "1", "e", "d", "h", "f", "x", "b")),
    Pair("m", listOf("m", "n", "M", "x", "w", "u", "min", "sin", "mm", "ms")),
    Pair("n", listOf("n", "a", "m", "r", "∧", "u", "x", "∩", "π", "cm", "sin", "dm", "·")),
    Pair("o", listOf("0", "o", "∘", "O", ".", "·")),
    Pair("p", listOf("p", "P", "ρ", "f", "F", "t")),
    Pair("q", listOf("q", "g", "y", "4", "G", "9", "r", "V", "a", "cot")),
    Pair("r", listOf("r", "n", "v", "m", "t", "+", "ν", "p", "·", ".")),
    Pair("s", listOf("s", "S", "5", "=", "g")),
    Pair("t", listOf("t", "+", "e", "E", "i", "l", "∈", "(", "f", "x")),
    Pair("u", listOf("u", "n", "a", "4", "U", "y", "m", "r", "9", "α")),
    Pair("v", listOf("v", "ν", "V", "∨", "r", "γ", "⊖", "dt", "dl")),
    Pair("w", listOf("w", "ω", "W", "N", "⊂", "n", "ms", "ha", "sin", "tan", "cos")),
    Pair("x", listOf("x", "×", "X", "⊗")),
    Pair("y", listOf("y", "g", "Y", "b", "4", "z", "t", "r", "cg")),
    Pair("z", listOf("z", "Z", "ℤ", "2", "=")),

    Pair("A", listOf("A", "H", "R", "t", "f", "K", "k", "λ", "ℝ")),
    Pair("B", listOf("B", "β", "D", "ℝ", "tan")),
    Pair("C", listOf("c", "C", "⊂", "(", "ℂ", "a", "<")),
    Pair("D", listOf("D", "B", "Δ", "P", "0", "b", "∩", "p")),
    Pair("E", listOf("E", "τ", "I", "±", "≡", "t", "≒", "F", "=", "π")),
    Pair("F", listOf("F", "f", "E", "Γ", "t", "I")),
    Pair("G", listOf("G", "a", "cot")),
    Pair("H", listOf("H", "4", "M", "A", "N")),
    Pair("I", listOf("I", "1", "±", "[", "E", "l", "Γ", "]", "=", "F")),
    Pair("J", listOf("J", "j", "5", "I", "]", "T")),
    Pair("K", listOf("K", "k", "κ")),
    Pair("L", listOf("L", "ι", "l", "1", "(", "2", "t")),
    Pair("M", listOf("M", "H", "µ", "N", "n", "m", "≠", "4", "u", "ℕ", "µs")),
    Pair("N", listOf("N", "ℕ", "M", "H")),
    Pair("O", listOf("0", "o", "O", "∘")),
    Pair("P", listOf("p", "P", "ρ")),
    Pair("Q", listOf("Q", "ℚ", "a", "α", "∝", "cl", "tan")),
    Pair("R", listOf("R", "ℝ", "k", "K", "κ", "r")),
    Pair("S", listOf("S", "s", "5", "∫", "ζ", "g", "G", "ξ")),
    Pair("T", listOf("T", "τ", "t", "+")),
    Pair("U", listOf("u", "U", "∪", "n", "K", "4", "k", "κ", "a", "υ", "dt")),
    Pair("V", listOf("V", "v", "∨", "ν", "⊖", "∪", "cl")),
    Pair("W", listOf("W", "w", "ω", "N", "hl", "ms", "ml", "tan")),
    Pair("X", listOf("X", "x", "×", "⊗")),
    Pair("Y", listOf("Y", "γ", "Υ", "y", "∯", "ℚ", "x", "'")),
    Pair("Z", listOf("z", "Z", "ℤ", "2", "E")),

    Pair("(", listOf("(", "1", "l", "|", "I", "ι", "t", "{", "⊆", "·")),
    Pair(")", listOf(")", "⟩", ",", ">", "'", "7", "y", "x", "·", ".")),
    Pair("{", listOf("{", "(", "[", "ξ", "∑", "ε", "Σ", "L")),
    Pair("}", listOf("}", ")", "]", "3", "ξ", "ζ")),
    Pair("[", listOf("[", "(", "{" )),
    Pair("]", listOf("]", ")", "}" )),

    Pair(".", listOf("·", ".", "-", "_", "=", "2", "r", "a", "s")),
    Pair("+", listOf("+", "t", "-", "_", "1", "⊥", "4", "x", "→", "=")),
    Pair("-", listOf("-", "_", "=", "+", "1", "P", "0", "r", "2")),
    Pair("×", listOf("×", "x", "X")),
    Pair("÷", listOf("÷", "=", "i", "≒", "-", "_", "+")),
    Pair("=", listOf("=", "-", "≃", "i", "_", "1", "I")),
    Pair(">", listOf("⟩", ">", "⊖", "7", "<", ")")),
    Pair("<", listOf("<", "⟨", "c", "∠", ">", "C", "a", "∂", "(", "cm", ".")),
    Pair("≥", listOf("≥", "2", "z", "ℤ", "Z", "⇔", "⊇", "=")),
    Pair("≤", listOf("≤", "∄", "⊆", "<")),

    Pair("±", listOf("±", "t", "+", "I", "⊥", "1", "f")),
    Pair("√", listOf("√", "r", "Γ", "v", "⊄", "N", "T", "ℕ", "t", "V")),
    Pair("∞", listOf("∞", "0", "n", "o", "cos", "cot", "sin", ".", "·")),
    Pair("∅", listOf("∅", "ϕ", "↔", "Φ", "9", "Q", "q", "g")),
    Pair("∩", listOf("∩", "n", "Π", "π", "r", "M", "Λ", "∏", "∧", ".")),
    Pair("∪", listOf("U", "∪", "υ", "u", "0", "v", "∨", "V", "O")),
    Pair("α", listOf("α", "∝", "a", "d", "0", "∂", "x", "o", "∞")),
    Pair("β", listOf("β", "∀", "ℕ", "B", "R", "ρ", "f", "cg", "cos")),
    Pair("γ", listOf("r", "γ", "n", "x", "T", "t", "ν", "Γ", "v")),
    Pair("θ", listOf("θ", "Θ", "⊖", "∝", "0", "Q", "∥", "cl", "cg", "kg", "tan")),
    Pair("π", listOf("π", "Π", "x", "lim")),
)
