plugins {
    id 'com.android.library'
}

android {
    namespace 'com.myscript.iink.uireferenceimplementation'

    compileSdk 36

    defaultConfig {
        minSdk 21
        targetSdk 36
        versionCode 4500
        versionName '4.5.0'

        vectorDrawables.useSupportLibrary true
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.5.1"
    implementation "com.google.code.gson:gson:2.10.1"
    api "com.myscript:iink:4.5.0"
}
