package com.knowre.android.myscript.iink.jiix


class PreDefinedCandidate(
    val label: String,
    val candidates: List<String>,
    val excludes: List<String>
)

val preDefinedCandidateInfos = listOf(
    PreDefinedCandidate("0", listOf("O", "0", "o", "·", "."), listOf("∘", "∫",)),
    PreDefinedCandidate("1", listOf("1", "|", "I", "l", "i", "t", "(", "+"), listOf("ι")),
    PreDefinedCandidate("2", listOf("2", "z", "Z", "1", "=", "3", "r", "a"), listOf()),
    PreDefinedCandidate("3", listOf("3", "}", "s", "1", "2", "z", "5"), listOf("ζ")),
    PreDefinedCandidate("4", listOf("4", "q", "9", "y", "a", "g", "cl"), listOf("cl")),
    PreDefinedCandidate("5", listOf("5", "s", "E", "J", "[", "F", "f", "S"), listOf("tan",  "ζ")),
    PreDefinedCandidate("6", listOf("6", "b", "f", "t", "G", "8", "(", "L"), listOf()),
    PreDefinedCandidate("7", listOf("7", "T", "2", "I", "1", "r"), listOf("τ","ζ")),
    PreDefinedCandidate("8", listOf("8", "g", "f", "s", "S", "&", "G", "5"), listOf("δ", "sin")),
    PreDefinedCandidate("9", listOf("9", "q", "a", "g", "G", "4"), listOf("ℚ", "cl")),

    PreDefinedCandidate("a", listOf("a", "α", "G", "A", "q", "d", "o", "n"), listOf("∝", "cl")),
    PreDefinedCandidate("b", listOf("b", "h", "6", "k"), listOf("ha", "tan")),
    PreDefinedCandidate("c", listOf("c", "C", "a", "<", "2", "(", "o"), listOf("⊂", "∠")),
    PreDefinedCandidate("d", listOf("d", "h", "k", "a", "α", "2", "t", "x"), listOf("dx", "λ")),
    PreDefinedCandidate("e", listOf("e", "c", "C", "l", "2", "r", "E", "a"), listOf()),
    PreDefinedCandidate("f", listOf("f", "t", "+", "F", "1", "l"), listOf()),
    PreDefinedCandidate("y", listOf("g", "y", "t", "q", "8", "f", "z", "2", "J", "r"), listOf("sin")),
    PreDefinedCandidate("h", listOf("h", "k", "K", "n", "4", "b", "t", "1"), listOf("κ", "hl")),
    PreDefinedCandidate("i", listOf("i", "I", "1", "j", "T", ";", "'", "t", "+"), listOf()),
    PreDefinedCandidate("j", listOf("j", "J", ")", "i", "I", ",", "g", "]", "1"), listOf()),
    PreDefinedCandidate("k", listOf("k", "K"), listOf("κ")),
    PreDefinedCandidate("l", listOf("l", "t", "1", "e", "d", "h", "f", "x", "b"), listOf()),
    PreDefinedCandidate("m", listOf("m", "n", "M", "x", "w", "u"), listOf("min", "sin", "mm", "ms")),
    PreDefinedCandidate("n", listOf("n", "a", "m", "r", "∧", "u", "x", "∩", "π", "·"), listOf("cm", "sin", "dm")),
    PreDefinedCandidate("o", listOf("0", "o", "O", ".", "·"), listOf("∘")),
    PreDefinedCandidate("p", listOf("p", "P", "ρ", "f", "F", "t"), listOf()),
    PreDefinedCandidate("q", listOf("q", "g", "y", "4", "G", "9", "r", "V", "a"), listOf("cot")),
    PreDefinedCandidate("r", listOf("r", "n", "v", "m", "t", "+", "p", "·", "."), listOf("ν")),
    PreDefinedCandidate("s", listOf("s", "S", "5", "=", "g"), listOf()),
    PreDefinedCandidate("t", listOf("t", "+", "e", "E", "i", "l", "(", "f", "x"), listOf("∈")),
    PreDefinedCandidate("u", listOf("u", "n", "a", "4", "U", "y", "m", "r", "9", "α"), listOf()),
    PreDefinedCandidate("v", listOf("v", "V", "∨", "r", "γ", "⊖"), listOf("ν", "dt", "dl")),
    PreDefinedCandidate("w", listOf("w", "W", "N", "⊂", "n"), listOf("ω", "ms", "ha", "sin", "tan", "cos")),
    PreDefinedCandidate("x", listOf("x", "×", "X"), listOf("⊗")),
    PreDefinedCandidate("y", listOf("y", "g", "Y", "b", "4", "z", "t", "r"), listOf("cg")),
    PreDefinedCandidate("z", listOf("z", "Z", "2", "="), listOf("ℤ")),

    PreDefinedCandidate("A", listOf("A", "H", "R", "t", "f", "K", "k"), listOf("λ", "ℝ")),
    PreDefinedCandidate("B", listOf("B", "β", "D"), listOf("ℝ", "tan")),
    PreDefinedCandidate("C", listOf("c", "C", "(", "a", "<"), listOf("⊂", "ℂ")),
    PreDefinedCandidate("D", listOf("D", "B", "P", "0", "b", "∩", "p"), listOf("Δ")),
    PreDefinedCandidate("E", listOf("E", "I", "±", "t", "F", "=", "π"), listOf("τ", "≡", "≒")),
    PreDefinedCandidate("F", listOf("F", "f", "E", "t", "I"), listOf("Γ", )),
    PreDefinedCandidate("G", listOf("G", "a"), listOf("cot")),
    PreDefinedCandidate("H", listOf("H", "4", "M", "A", "N"), listOf()),
    PreDefinedCandidate("I", listOf("I", "1", "±", "[", "E", "l", "]", "=", "F"), listOf("Γ")),
    PreDefinedCandidate("J", listOf("J", "j", "5", "I", "]", "T"), listOf()),
    PreDefinedCandidate("K", listOf("K", "k"), listOf("κ")),
    PreDefinedCandidate("L", listOf("L", "l", "1", "(", "2", "t"), listOf("ι")),
    PreDefinedCandidate("M", listOf("M", "H", "N", "n", "m", "≠", "4", "u"), listOf("µ", "ℕ", "µs")),
    PreDefinedCandidate("N", listOf("N", "M", "H"), listOf("ℕ")),
    PreDefinedCandidate("O", listOf("0", "o", "O"), listOf("∘")),
    PreDefinedCandidate("P", listOf("p", "P"), listOf("ρ")),
    PreDefinedCandidate("Q", listOf("Q", "a", "α"), listOf("ℚ", "∝", "cl", "tan")),
    PreDefinedCandidate("R", listOf("R", "k", "K", "r"), listOf("ℝ", "κ")),
    PreDefinedCandidate("S", listOf("S", "s", "5", "g", "G"), listOf("∫", "ζ", "ξ")),
    PreDefinedCandidate("T", listOf("T", "t", "+"), listOf("τ")),
    PreDefinedCandidate("U", listOf("u", "U", "∪", "n", "K", "4", "k", "a"), listOf("κ", "υ", "dt")),
    PreDefinedCandidate("V", listOf("V", "v", "∨", "⊖", "∪"), listOf("ν", "cl")),
    PreDefinedCandidate("W", listOf("W", "w", "N"), listOf("hl", "ω", "ms", "ml", "tan")),
    PreDefinedCandidate("X", listOf("X", "x", "×"), listOf("⊗")),
    PreDefinedCandidate("Y", listOf("Y", "γ", "Υ", "y", "x", "'"), listOf("∯", "ℚ")),
    PreDefinedCandidate("Z", listOf("z", "Z", "2", "E"), listOf("ℤ")),

    PreDefinedCandidate("(", listOf("(", "1", "{", "[", "l", "|", "I", "t", "{", "·"), listOf("ι", "⊆")),
    PreDefinedCandidate(")", listOf(")", "1", "}", "]", ">", ",", "'", "7", "y", "x", "·", "."), listOf("⟩")),
    PreDefinedCandidate("{", listOf("{", "(", "[", "L"), listOf("ξ", "∑", "ε", "Σ")),
    PreDefinedCandidate("}", listOf("}", ")", "]"), listOf("3", "ξ", "ζ")),
    PreDefinedCandidate("[", listOf("[", "(", "{" ), listOf()),
    PreDefinedCandidate("]", listOf("]", ")", "}" ), listOf()),

    PreDefinedCandidate(".", listOf("·", ".", "-", "_", "=", "2", "r", "a", "s"), listOf()),
    PreDefinedCandidate("+", listOf("+", "t", "-", "_", "1", "4", "x", "="), listOf("⊥", "→")),
    PreDefinedCandidate("-", listOf("-", "_", "=", "+", "1", "P", "0", "r", "2"), listOf()),
    PreDefinedCandidate("×", listOf("×", "x", "X"), listOf()),
    PreDefinedCandidate("÷", listOf("÷", "=", "i", "-", "_", "+"), listOf("≒")),
    PreDefinedCandidate("=", listOf("=", "-", "i", "_", "1", "I"), listOf("≃")),
    PreDefinedCandidate(">", listOf(">", "⊖", "7", "<", ")"), listOf("⟩")),
    PreDefinedCandidate("<", listOf("<", "c", ">", "C", "a", "(", "."), listOf("⟨", "cm", "∂", "∠")),
    PreDefinedCandidate("≥", listOf("≥", "2", "z", "Z", "="), listOf("ℤ", "⇔", "⊇")),
    PreDefinedCandidate("≤", listOf("≤", "<"), listOf("∄", "⊆")),

    PreDefinedCandidate("±", listOf("±", "t", "+", "I", "1", "f"), listOf("⊥")),
    PreDefinedCandidate("√", listOf("√", "r", "v", "N", "T", "t", "V"), listOf("Γ", "ℕ", "⊄")),
    PreDefinedCandidate("∞", listOf("∞", "0", "n", "o", ".", "·"), listOf("cos", "cot", "sin")),
    PreDefinedCandidate("∅", listOf("∅", "ϕ", "Φ", "9", "Q", "q", "g"), listOf("↔")),
    PreDefinedCandidate("∩", listOf("∩", "n", "Π", "π", "r", "M", "Λ", "∧", "."), listOf("∏")),
    PreDefinedCandidate("∪", listOf("U", "∪", "u", "0", "v", "∨", "V", "O"), listOf("υ")),
    PreDefinedCandidate("α", listOf("α", "a", "d", "0", "x", "o", "∞"), listOf("∝", "∂")),
    PreDefinedCandidate("β", listOf("β", "B", "R", "ρ", "f"), listOf("∀", "ℕ", "cg", "cos")),
    PreDefinedCandidate("γ", listOf("r", "γ", "n", "x", "T", "t", "v"), listOf("ν", "Γ")),
    PreDefinedCandidate("θ", listOf("θ", "Θ", "⊖", "∝", "0", "Q"), listOf("∥", "cl", "cg", "kg", "tan")),
    PreDefinedCandidate("π", listOf("π", "Π", "x"), listOf("lim")),
)
